local pm = require("playerManager")
local extrasounds = require("extrasounds")

local costume = {}

function costume.onInit(p)
	Audio.sounds[1].sfx  = Audio.SfxOpen("costumes/mario/PrincessRescue/player-jump.ogg")
	Audio.sounds[2].sfx  = Audio.SfxOpen("costumes/mario/PrincessRescue/stomped.ogg")
	Audio.sounds[3].sfx  = Audio.SfxOpen("costumes/mario/PrincessRescue/block-hit.ogg")
	extrasounds.playersoundid4  = Audio.SfxOpen("costumes/mario/PrincessRescue/block-smash.ogg")
	Audio.sounds[5].sfx  = Audio.SfxOpen("costumes/mario/PrincessRescue/player-shrink.ogg")
	Audio.sounds[6].sfx  = Audio.SfxOpen("costumes/mario/PrincessRescue/player-grow.ogg")
	extrasounds.playersoundid7  = Audio.SfxOpen("costumes/mario/PrincessRescue/mushroom.ogg")
	Audio.sounds[8].sfx  = Audio.SfxOpen("costumes/mario/PrincessRescue/player-died.ogg")
	Audio.sounds[9].sfx  = Audio.SfxOpen("costumes/mario/PrincessRescue/shell-hit.ogg")
	Audio.sounds[10].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/player-slide.ogg")
	extrasounds.playersoundid14 = Audio.SfxOpen("costumes/mario/PrincessRescue/coin.ogg")
	extrasounds.playersoundid15 = Audio.SfxOpen("costumes/mario/PrincessRescue/1up.ogg")
	Audio.sounds[17].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/warp.ogg")
	Audio.sounds[18].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/fireball.ogg")
	Audio.sounds[22].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/bullet-bill.ogg")
	Audio.sounds[23].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/grab.ogg")
	Audio.sounds[24].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/spring.ogg")
	Audio.sounds[29].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/do.ogg")
	Audio.sounds[31].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/key.ogg")
	Audio.sounds[33].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/tail.ogg")
	Audio.sounds[34].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/racoon.ogg")
	Audio.sounds[37].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/thwomp.ogg")
	Audio.sounds[42].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/npc-fireball.ogg")
	Audio.sounds[43].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/fireworks.ogg")
	Audio.sounds[46].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/door.ogg")
	Audio.sounds[48].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/yoshi.ogg")
	Audio.sounds[51].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/yoshi-egg.ogg")
	Audio.sounds[52].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/got-star.ogg")
	Audio.sounds[54].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/player-died2.ogg")
	Audio.sounds[73].sfx = Audio.SfxOpen("costumes/mario/PrincessRescue/grab2.ogg")
	
	Defines.player_walkspeed = 4
	Defines.player_runspeed = 4
	Defines.jumpheight = 20
	Defines.jumpheight_bounce = 32
	Defines.player_grav = 0.6
end

function costume.onCleanup(p)
	Audio.sounds[1].sfx  = nil	
	Audio.sounds[2].sfx  = nil
	Audio.sounds[3].sfx  = nil
	Audio.sounds[4].sfx  = nil
	Audio.sounds[5].sfx  = nil
	Audio.sounds[6].sfx  = nil
	Audio.sounds[7].sfx  = nil
	Audio.sounds[8].sfx  = nil
	Audio.sounds[9].sfx  = nil
	Audio.sounds[10].sfx = nil
	Audio.sounds[11].sfx = nil
	Audio.sounds[12].sfx = nil
	Audio.sounds[13].sfx = nil
	extrasounds.playersoundid14 = Audio.SfxOpen(Misc.resolveSoundFile("coin.ogg"))
	extrasounds.playersoundid15 = Audio.SfxOpen(Misc.resolveSoundFile("1up.ogg"))
	Audio.sounds[16].sfx = nil
	Audio.sounds[17].sfx = nil
	extrasounds.playersoundid18 = Audio.SfxOpen(Misc.resolveSoundFile("fireball.ogg"))
	Audio.sounds[19].sfx = nil
	Audio.sounds[20].sfx = nil
	Audio.sounds[21].sfx = nil
	Audio.sounds[22].sfx = nil
	Audio.sounds[23].sfx = nil
	Audio.sounds[24].sfx = nil
	Audio.sounds[25].sfx = nil
	Audio.sounds[29].sfx = nil
	Audio.sounds[31].sfx = nil
	Audio.sounds[32].sfx = nil
	Audio.sounds[33].sfx = nil
	Audio.sounds[34].sfx = nil
	Audio.sounds[35].sfx = nil
	Audio.sounds[36].sfx = nil
	Audio.sounds[37].sfx = nil
	Audio.sounds[38].sfx = nil
	Audio.sounds[39].sfx = nil
	Audio.sounds[41].sfx = nil
	Audio.sounds[42].sfx = nil
	Audio.sounds[43].sfx = nil
	Audio.sounds[44].sfx = nil
	Audio.sounds[46].sfx = nil
	Audio.sounds[47].sfx = nil
	Audio.sounds[48].sfx = nil
	Audio.sounds[49].sfx = nil
	Audio.sounds[50].sfx = nil
	Audio.sounds[51].sfx = nil
	Audio.sounds[52].sfx = nil
	Audio.sounds[54].sfx = nil
	Audio.sounds[55].sfx = nil
	Audio.sounds[56].sfx = nil
	Audio.sounds[57].sfx = nil
	Audio.sounds[58].sfx = nil
	Audio.sounds[59].sfx = nil
	Audio.sounds[61].sfx = nil
	Audio.sounds[62].sfx = nil
	Audio.sounds[63].sfx = nil
	Audio.sounds[71].sfx = nil
	Audio.sounds[72].sfx = nil
	Audio.sounds[73].sfx = nil
	Audio.sounds[75].sfx = nil
	Audio.sounds[76].sfx = nil
	Audio.sounds[77].sfx = nil
	Audio.sounds[78].sfx = nil
	Audio.sounds[79].sfx = nil
	Audio.sounds[80].sfx = nil
	Audio.sounds[81].sfx = nil
	Audio.sounds[82].sfx = nil
	Audio.sounds[91].sfx = nil
	extrasounds.playersoundid92 = Audio.SfxOpen(Misc.resolveSoundFile("sound/sprout-vine.ogg"))
	extrasounds.playersoundid93 = Audio.SfxOpen(Misc.resolveSoundFile("sound/iceball.ogg"))
	extrasounds.playersoundid94 = Audio.SfxOpen(Misc.resolveSoundFile("sound/yi_freeze.ogg"))
	extrasounds.playersoundid95 = Audio.SfxOpen(Misc.resolveSoundFile("sound/yi_icebreak.ogg"))
	extrasounds.playersoundid96 = Audio.SfxOpen(Misc.resolveSoundFile("sound/2up.ogg"))
	extrasounds.playersoundid97 = Audio.SfxOpen(Misc.resolveSoundFile("sound/3up.ogg"))
	extrasounds.playersoundid98 = Audio.SfxOpen(Misc.resolveSoundFile("sound/5up.ogg"))
	extrasounds.playersoundid99 = Audio.SfxOpen(Misc.resolveSoundFile("sound/dragon-coin-get2.ogg"))
	extrasounds.playersoundid100 = Audio.SfxOpen(Misc.resolveSoundFile("sound/dragon-coin-get3.ogg"))
	extrasounds.playersoundid101 = Audio.SfxOpen(Misc.resolveSoundFile("sound/dragon-coin-get4.ogg"))
	extrasounds.playersoundid102 = Audio.SfxOpen(Misc.resolveSoundFile("sound/dragon-coin-get5.ogg"))
	extrasounds.playersoundid103 = Audio.SfxOpen(Misc.resolveSoundFile("sound/cherry.ogg"))
	Defines.jumpheight = 20
	Defines.player_walkspeed = 3
	Defines.player_runspeed = 6
	Defines.jumpheight_bounce = 32
	Defines.player_grav = 0.4
end

return costume