local pm = require("playerManager")
local extrasounds = require("extrasounds")

local costume = {}

function costume.onInit(p)
    extrasounds.sound.sfx[1] = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/player-jump.ogg")
    Audio.sounds[2].sfx  = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/stomped.ogg")
    Audio.sounds[3].sfx  = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/block-hit.ogg")
    extrasounds.sound.sfx[4]  = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/block-smash.ogg")
    Audio.sounds[5].sfx  = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/player-shrink.ogg")
    Audio.sounds[6].sfx  = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/player-grow.ogg")
    extrasounds.sound.sfx[7]  = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/mushroom.ogg")
    extrasounds.sound.sfx[8]  = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/player-died.ogg")
    Audio.sounds[9].sfx  = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/shell-hit.ogg")
    extrasounds.sound.sfx[10] = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/player-slide.ogg")
    Audio.sounds[11].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/item-dropped.ogg")
    Audio.sounds[12].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/has-item.ogg")
    Audio.sounds[13].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/camera-change.ogg")
    extrasounds.sound.sfx[14]  = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/coin.ogg")
    extrasounds.sound.sfx[15]  = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/1up.ogg")
    Audio.sounds[16].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/lava.ogg")
    Audio.sounds[17].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/warp.ogg")
    extrasounds.sound.sfx[18]  = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/fireball.ogg")
    Audio.sounds[19].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/level-win.ogg")
    Audio.sounds[20].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/boss-beat.ogg")
    Audio.sounds[21].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/dungeon-win.ogg")
    Audio.sounds[22].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/bullet-bill.ogg")
    Audio.sounds[23].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/grab.ogg")
    Audio.sounds[24].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/spring.ogg")
    Audio.sounds[25].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/hammer.ogg")
    Audio.sounds[29].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/do.ogg")
    Audio.sounds[31].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/key.ogg")
    Audio.sounds[32].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/pswitch.ogg")
    extrasounds.sound.sfx[33] = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/tail.ogg")
    Audio.sounds[34].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/racoon.ogg")
    Audio.sounds[35].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/boot.ogg")
    extrasounds.sound.sfx[36] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/toad/05-SMB2-Retro-Red/smash.ogg"))
    Audio.sounds[37].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/thwomp.ogg")
    Audio.sounds[38].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/birdo-spit.ogg")
    extrasounds.sound.sfx[39] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/toad/05-SMB2-Retro-Red/birdo-hit.ogg"))
    Audio.sounds[41].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/birdo-beat.ogg")
    extrasounds.sound.sfx[42] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/toad/05-SMB2-Retro-Red/npc-fireball.ogg"))
    extrasounds.sound.sfx[43] = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/fireworks.ogg")
    Audio.sounds[44].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/bowser-killed.ogg")
    Audio.sounds[46].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/door.ogg")
    Audio.sounds[47].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/message.ogg")
    Audio.sounds[48].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/yoshi.ogg")
    Audio.sounds[49].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/yoshi-hurt.ogg")
    Audio.sounds[50].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/yoshi-tongue.ogg")
    Audio.sounds[51].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/yoshi-egg.ogg")
    Audio.sounds[52].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/got-star.ogg")
    Audio.sounds[54].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/player-died2.ogg")
    Audio.sounds[55].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/yoshi-swallow.ogg")
    Audio.sounds[57].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/dry-bones.ogg")
    Audio.sounds[58].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/smw-checkpoint.ogg")
    extrasounds.sound.sfx[59]  = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/dragon-coin.ogg")
    Audio.sounds[61].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/smw-blaarg.ogg")
    Audio.sounds[62].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/wart-bubble.ogg")
    Audio.sounds[63].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/wart-die.ogg")
    Audio.sounds[71].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/climbing.ogg")
    Audio.sounds[72].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/swim.ogg")
    Audio.sounds[73].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/grab2.ogg")
    --Audio.sounds[74].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/saw.ogg")
    Audio.sounds[75].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/smb2-throw.ogg")
    Audio.sounds[76].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/smb2-hit.ogg")
    Audio.sounds[91].sfx = Audio.SfxOpen("costumes/toad/05-SMB2-Retro-Red/bubble.ogg")
end

function costume.onCleanup(p)
    extrasounds.sound.sfx[1] = nil    
    Audio.sounds[2].sfx  = nil
    Audio.sounds[3].sfx  = nil
    extrasounds.sound.sfx[4] = nil
    Audio.sounds[5].sfx  = nil
    Audio.sounds[6].sfx  = nil
    extrasounds.sound.sfx[7] = nil
    extrasounds.sound.sfx[8] = nil
    Audio.sounds[9].sfx  = nil
    extrasounds.sound.sfx[10] = nil
    Audio.sounds[11].sfx = nil
    Audio.sounds[12].sfx = nil
    Audio.sounds[13].sfx = nil
    extrasounds.sound.sfx[14] = nil
    extrasounds.sound.sfx[15] = nil
    Audio.sounds[16].sfx = nil
    Audio.sounds[17].sfx = nil
    extrasounds.sound.sfx[18] = nil
    Audio.sounds[19].sfx = nil
    Audio.sounds[20].sfx = nil
    Audio.sounds[21].sfx = nil
    Audio.sounds[22].sfx = nil
    Audio.sounds[23].sfx = nil
    Audio.sounds[24].sfx = nil
    Audio.sounds[25].sfx = nil
    Audio.sounds[29].sfx = nil
    Audio.sounds[31].sfx = nil
    Audio.sounds[32].sfx = nil
    extrasounds.sound.sfx[33] = nil
    Audio.sounds[34].sfx = nil
    Audio.sounds[35].sfx = nil
    extrasounds.sound.sfx[36] = nil
    Audio.sounds[37].sfx = nil
    Audio.sounds[38].sfx = nil
    extrasounds.sound.sfx[39] = nil
    Audio.sounds[41].sfx = nil
    extrasounds.sound.sfx[42] = nil
    extrasounds.sound.sfx[43] = nil
    Audio.sounds[44].sfx = nil
    Audio.sounds[46].sfx = nil
    Audio.sounds[47].sfx = nil
    Audio.sounds[48].sfx = nil
    Audio.sounds[49].sfx = nil
    Audio.sounds[50].sfx = nil
    Audio.sounds[51].sfx = nil
    Audio.sounds[52].sfx = nil
    Audio.sounds[54].sfx = nil
    Audio.sounds[55].sfx = nil
    Audio.sounds[56].sfx = nil
    Audio.sounds[57].sfx = nil
    Audio.sounds[58].sfx = nil
    extrasounds.sound.sfx[59] = nil
    Audio.sounds[61].sfx = nil
    Audio.sounds[62].sfx = nil
    Audio.sounds[63].sfx = nil
    Audio.sounds[71].sfx = nil
    Audio.sounds[72].sfx = nil
    Audio.sounds[73].sfx = nil
    Audio.sounds[75].sfx = nil
    Audio.sounds[76].sfx = nil
    Audio.sounds[77].sfx = nil
    Audio.sounds[78].sfx = nil
    Audio.sounds[79].sfx = nil
    Audio.sounds[80].sfx = nil
    Audio.sounds[81].sfx = nil
    Audio.sounds[82].sfx = nil
    Audio.sounds[91].sfx = nil
    extrasounds.sound.sfx92 = Audio.SfxOpen(Misc.resolveSoundFile("sound/sprout-vine.ogg"))
    extrasounds.sound.sfx93 = Audio.SfxOpen(Misc.resolveSoundFile("sound/iceball.ogg"))
    extrasounds.sound.sfx94 = Audio.SfxOpen(Misc.resolveSoundFile("sound/yi-freeze.ogg"))
    extrasounds.sound.sfx95 = Audio.SfxOpen(Misc.resolveSoundFile("sound/yi-icebreak.ogg"))
    extrasounds.sound.sfx96 = Audio.SfxOpen(Misc.resolveSoundFile("sound/2up.ogg"))
    extrasounds.sound.sfx97 = Audio.SfxOpen(Misc.resolveSoundFile("sound/3up.ogg"))
    extrasounds.sound.sfx98 = Audio.SfxOpen(Misc.resolveSoundFile("sound/5up.ogg"))
    extrasounds.sound.sfx99 = Audio.SfxOpen(Misc.resolveSoundFile("sound/dragon-coin-get2.ogg"))
    extrasounds.sound.sfx100 = Audio.SfxOpen(Misc.resolveSoundFile("sound/dragon-coin-get3.ogg"))
    extrasounds.sound.sfx101 = Audio.SfxOpen(Misc.resolveSoundFile("sound/dragon-coin-get4.ogg"))
    extrasounds.sound.sfx102 = Audio.SfxOpen(Misc.resolveSoundFile("sound/dragon-coin-get5.ogg"))
    extrasounds.sound.sfx103 = Audio.SfxOpen(Misc.resolveSoundFile("sound/cherry.ogg"))
    extrasounds.sound.sfx104 = Audio.SfxOpen(Misc.resolveSoundFile("sound/explode.ogg")) --SMB2 Explosion
    extrasounds.sound.sfx105 = Audio.SfxOpen(Misc.resolveSoundFile("sound/hammerthrow.ogg")) --Player hammer throw
    extrasounds.sound.sfx106 = Audio.SfxOpen(Misc.resolveSoundFile("sound/combo1.ogg")) --Shell hit 2
    extrasounds.sound.sfx107 = Audio.SfxOpen(Misc.resolveSoundFile("sound/combo2.ogg")) --Shell hit 3
    extrasounds.sound.sfx108 = Audio.SfxOpen(Misc.resolveSoundFile("sound/combo3.ogg")) --Shell hit 4
    extrasounds.sound.sfx109 = Audio.SfxOpen(Misc.resolveSoundFile("sound/combo4.ogg")) --Shell hit 5
    extrasounds.sound.sfx110 = Audio.SfxOpen(Misc.resolveSoundFile("sound/combo5.ogg")) --Shell hit 6
    extrasounds.sound.sfx111 = Audio.SfxOpen(Misc.resolveSoundFile("sound/combo6.ogg")) --Shell hit 7
    extrasounds.sound.sfx112 = Audio.SfxOpen(Misc.resolveSoundFile("sound/combo7.ogg")) --Shell hit 8
end

return costume;