local pm = require("playerManager")
local extrasounds = require("extrasounds")

local costume = {}

local eventsRegistered = false

function costume.onInit(p)
    extrasounds.sound.sfx[1] = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/player-jump.ogg")
    Audio.sounds[2].sfx  = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/stomped.ogg")
    Audio.sounds[3].sfx  = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/block-hit.ogg")
    extrasounds.sound.sfx[4]  = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/block-smash.ogg")
    Audio.sounds[5].sfx  = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/player-shrink.ogg")
    Audio.sounds[6].sfx  = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/player-grow.ogg")
    extrasounds.sound.sfx[7]  = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/mushroom.ogg")
    extrasounds.sound.sfx[8]  = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/player-died.ogg")
    Audio.sounds[9].sfx  = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/shell-hit.ogg")
    extrasounds.sound.sfx[10] = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/player-slide.ogg")
    Audio.sounds[11].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/item-dropped.ogg")
    Audio.sounds[12].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/has-item.ogg")
    Audio.sounds[13].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/camera-change.ogg")
    extrasounds.sound.sfx[14] = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/coin.ogg")
    extrasounds.sound.sfx[15] = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/1up.ogg")
    Audio.sounds[16].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/lava.ogg")
    Audio.sounds[17].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/warp.ogg")
    extrasounds.sound.sfx[18] = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/fireball.ogg")
    Audio.sounds[19].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/level-win.ogg")
    Audio.sounds[20].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/boss-beat.ogg")
    Audio.sounds[21].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/dungeon-win.ogg")
    Audio.sounds[22].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/bullet-bill.ogg")
    Audio.sounds[23].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/grab.ogg")
    Audio.sounds[24].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/spring.ogg")
    Audio.sounds[25].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/hammer.ogg")
    Audio.sounds[29].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/do.ogg")
    Audio.sounds[31].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/key.ogg")
    Audio.sounds[32].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/pswitch.ogg")
    extrasounds.sound.sfx[33] = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/tail.ogg")
    Audio.sounds[34].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/racoon.ogg")
    Audio.sounds[35].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/boot.ogg")
    extrasounds.sound.sfx[36] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/smash.ogg"))
    Audio.sounds[37].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/thwomp.ogg")
    Audio.sounds[38].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/birdo-spit.ogg")
    extrasounds.sound.sfx[39] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/birdo-hit.ogg"))
    Audio.sounds[41].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/birdo-beat.ogg")
    extrasounds.sound.sfx[42] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/npc-fireball.ogg"))
    extrasounds.sound.sfx[43] = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/fireworks.ogg")
    Audio.sounds[44].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/bowser-killed.ogg")
    Audio.sounds[46].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/door.ogg")
    Audio.sounds[47].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/message.ogg")
    Audio.sounds[48].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/yoshi.ogg")
    Audio.sounds[49].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/yoshi-hurt.ogg")
    Audio.sounds[50].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/yoshi-tongue.ogg")
    Audio.sounds[51].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/yoshi-egg.ogg")
    Audio.sounds[52].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/got-star.ogg")
    Audio.sounds[54].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/player-died2.ogg")
    Audio.sounds[55].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/yoshi-swallow.ogg")
    Audio.sounds[57].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/dry-bones.ogg")
    Audio.sounds[58].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/smw-checkpoint.ogg")
    extrasounds.sound.sfx[59] = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/dragon-coin.ogg")
    Audio.sounds[61].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/smw-blaarg.ogg")
    Audio.sounds[62].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/wart-bubble.ogg")
    Audio.sounds[63].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/wart-die.ogg")
    Audio.sounds[71].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/climbing.ogg")
    Audio.sounds[72].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/swim.ogg")
    Audio.sounds[73].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/grab2.ogg")
    --Audio.sounds[74].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/saw.ogg")
    Audio.sounds[75].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/smb2-throw.ogg")
    Audio.sounds[76].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/smb2-hit.ogg")
    Audio.sounds[91].sfx = Audio.SfxOpen("costumes/luigi/03-SMB1-Retro-Modern/bubble.ogg")
    extrasounds.sound.sfx[92] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/sprout-vine.ogg")) --Vine sprout
    extrasounds.sound.sfx[93] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/iceball.ogg")) --Iceball
    extrasounds.sound.sfx[96] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/2up.ogg")) --2UP
    extrasounds.sound.sfx[97] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/3up.ogg")) --3UP
    extrasounds.sound.sfx[98] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/5up.ogg")) --5UP
    extrasounds.sound.sfx[99] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/dragon-coin-get2.ogg")) --Dragon Coin #2
    extrasounds.sound.sfx[100] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/dragon-coin-get3.ogg")) --Dragon Coin #3
    extrasounds.sound.sfx[101] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/dragon-coin-get4.ogg")) --Dragon Coin #4
    extrasounds.sound.sfx[102] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/dragon-coin-get5.ogg")) --Dragon Coin #5
    extrasounds.sound.sfx[103] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/cherry.ogg")) --Cherry
    extrasounds.sound.sfx[104] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/explode.ogg")) --SMB2 Explosion
    extrasounds.sound.sfx[105] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/hammerthrow.ogg")) --Player hammer throw
    extrasounds.sound.sfx[106] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/combo1.ogg")) --Combo 1
    extrasounds.sound.sfx[107] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/combo2.ogg")) --Combo 2
    extrasounds.sound.sfx[108] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/combo3.ogg")) --Combo 3
    extrasounds.sound.sfx[109] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/combo4.ogg")) --Combo 4
    extrasounds.sound.sfx[110] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/combo5.ogg")) --Combo 5
    extrasounds.sound.sfx[111] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/combo6.ogg")) --Combo 6
    extrasounds.sound.sfx[112] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/combo7.ogg")) --Combo 7
    extrasounds.sound.sfx[113] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/score-tally.ogg")) --Score tally
    extrasounds.sound.sfx[114] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/score-tally-end.ogg")) --Score tally end
    extrasounds.sound.sfx[115] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/bowser-fire.ogg")) --Bowser fire
    extrasounds.sound.sfx[116] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/boomerang.ogg")) --Boomerang
    extrasounds.sound.sfx[117] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/smb2-charge.ogg")) --SMB2 Charge
    extrasounds.sound.sfx[118] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/stopwatch.ogg")) --Stopwatch
    extrasounds.sound.sfx[119] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/whale-spout.ogg"))
    extrasounds.sound.sfx[120] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/door-reveal.ogg"))
    extrasounds.sound.sfx[121] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/p-wing.ogg"))
    extrasounds.sound.sfx[122] = Audio.SfxOpen(Misc.resolveSoundFile("wand-moving.ogg"))
    extrasounds.sound.sfx[123] = Audio.SfxOpen(Misc.resolveSoundFile("wand-whoosh.ogg"))
    extrasounds.sound.sfx[124] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/hop.ogg"))
    extrasounds.sound.sfx[125] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/smash-big.ogg"))
    extrasounds.sound.sfx[126] = Audio.SfxOpen(Misc.resolveSoundFile("smb2-hitenemy.ogg")) --SMB2 Hit Enemy
    extrasounds.sound.sfx[127] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/boss-fall.ogg"))
    extrasounds.sound.sfx[128] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/boss-lava.ogg"))
    extrasounds.sound.sfx[129] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/boss-shrink.ogg"))
    extrasounds.sound.sfx[130] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/boss-shrink-done.ogg"))
    extrasounds.sound.sfx[131] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/hp-get.ogg"))
    extrasounds.sound.sfx[132] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/hp-max.ogg"))
    extrasounds.sound.sfx[133] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/cape-feather.ogg"))
    extrasounds.sound.sfx[134] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/cape-fly.ogg"))
    extrasounds.sound.sfx[135] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/flag-slide.ogg"))
    extrasounds.sound.sfx[136] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/smb1-exit.ogg")) --SMB1 Exit
    extrasounds.sound.sfx[137] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/smb2-clear.ogg"))
    extrasounds.sound.sfx[138] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/smb1-world-clear.ogg"))
    extrasounds.sound.sfx[139] = Audio.SfxOpen(Misc.resolveSoundFile("smb1-underground-overworld.ogg"))
    extrasounds.sound.sfx[140] = Audio.SfxOpen(Misc.resolveSoundFile("smb1-underground-desert.ogg"))
    extrasounds.sound.sfx[141] = Audio.SfxOpen(Misc.resolveSoundFile("smb1-underground-sky.ogg"))
    extrasounds.sound.sfx[142] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/goaltape-countdown-start.ogg"))
    extrasounds.sound.sfx[143] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/goaltape-countdown-loop.ogg"))
    extrasounds.sound.sfx[144] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/goaltape-countdown-end.ogg"))
    extrasounds.sound.sfx[145] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/goaltape-irisout.ogg"))
    extrasounds.sound.sfx[146] = Audio.SfxOpen(Misc.resolveSoundFile("smw-exit-orb.ogg"))
    extrasounds.sound.sfx[147] = Audio.SfxOpen(Misc.resolveSoundFile("ace-coins-5.ogg"))
    extrasounds.sound.sfx[148] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/door-close.ogg"))
    extrasounds.sound.sfx[149] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/sprout-megashroom.ogg"))
    extrasounds.sound.sfx[150] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/0up.ogg"))
    extrasounds.sound.sfx[151] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/correct.ogg"))
    extrasounds.sound.sfx[152] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/wrong.ogg"))
    extrasounds.sound.sfx[153] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/castle-destroy.ogg"))
    extrasounds.sound.sfx[154] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/twirl.ogg"))
    extrasounds.sound.sfx[155] = Audio.SfxOpen(Misc.resolveSoundFile("fireball-hit.ogg")) --Fireball hit
    extrasounds.sound.sfx[156] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/shell-grab.ogg")) --Shell grab
    extrasounds.sound.sfx[157] = Audio.SfxOpen(Misc.resolveSoundFile("ice-melt.ogg"))
    extrasounds.sound.sfx[158] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/player-jump2.ogg"))
    extrasounds.sound.sfx[159] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/ground-pound.ogg"))
    extrasounds.sound.sfx[160] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/ground-pound-hit.ogg"))
    extrasounds.sound.sfx[161] = Audio.SfxOpen(Misc.resolveSoundFile("zelda-fireball.ogg"))
    extrasounds.sound.sfx[162] = Audio.SfxOpen(Misc.resolveSoundFile("zelda-iceball.ogg"))
    extrasounds.sound.sfx[163] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/pballoon.ogg"))
    extrasounds.sound.sfx[164] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/peach-cry.ogg"))
    extrasounds.sound.sfx[165] = Audio.SfxOpen(Misc.resolveSoundFile("timeout.ogg"))
    extrasounds.sound.sfx[166] = Audio.SfxOpen(Misc.resolveSoundFile("costumes/luigi/03-SMB1-Retro-Modern/flyinghammer-throw.ogg"))
    eventsRegistered = true
end

function costume.onCleanup(p)
    extrasounds.sound.sfx[1] = nil    
    Audio.sounds[2].sfx  = nil
    Audio.sounds[3].sfx  = nil
    Audio.sounds[4].sfx  = nil
    Audio.sounds[5].sfx  = nil
    Audio.sounds[6].sfx  = nil
    Audio.sounds[7].sfx  = nil
    extrasounds.sound.sfx[8] = nil
    Audio.sounds[9].sfx  = nil
    extrasounds.sound.sfx[10] = nil
    Audio.sounds[11].sfx = nil
    Audio.sounds[12].sfx = nil
    Audio.sounds[13].sfx = nil
    extrasounds.sound.sfx[14] = Audio.SfxOpen(Misc.resolveSoundFile("sound/coin.ogg"))
    extrasounds.sound.sfx[15] = Audio.SfxOpen(Misc.resolveSoundFile("sound/1up.ogg"))
    Audio.sounds[16].sfx = nil
    Audio.sounds[17].sfx = nil
    extrasounds.sound.sfx[18] = Audio.SfxOpen(Misc.resolveSoundFile("sound/fireball.ogg"))
    Audio.sounds[19].sfx = nil
    Audio.sounds[20].sfx = nil
    Audio.sounds[21].sfx = nil
    Audio.sounds[22].sfx = nil
    Audio.sounds[23].sfx = nil
    Audio.sounds[24].sfx = nil
    Audio.sounds[25].sfx = nil
    Audio.sounds[29].sfx = nil
    Audio.sounds[31].sfx = nil
    Audio.sounds[32].sfx = nil
    extrasounds.sound.sfx[33] = nil
    Audio.sounds[34].sfx = nil
    Audio.sounds[35].sfx = nil
    extrasounds.sound.sfx[36] = nil
    Audio.sounds[37].sfx = nil
    Audio.sounds[38].sfx = nil
    extrasounds.sound.sfx[39] = nil
    Audio.sounds[41].sfx = nil
    extrasounds.sound.sfx[42] = nil
    extrasounds.sound.sfx[43] = nil
    Audio.sounds[44].sfx = nil
    Audio.sounds[46].sfx = nil
    Audio.sounds[47].sfx = nil
    Audio.sounds[48].sfx = nil
    Audio.sounds[49].sfx = nil
    Audio.sounds[50].sfx = nil
    Audio.sounds[51].sfx = nil
    Audio.sounds[52].sfx = nil
    Audio.sounds[54].sfx = nil
    Audio.sounds[55].sfx = nil
    Audio.sounds[56].sfx = nil
    Audio.sounds[57].sfx = nil
    Audio.sounds[58].sfx = nil
    Audio.sounds[59].sfx = nil
    Audio.sounds[61].sfx = nil
    Audio.sounds[62].sfx = nil
    Audio.sounds[63].sfx = nil
    Audio.sounds[71].sfx = nil
    Audio.sounds[72].sfx = nil
    Audio.sounds[73].sfx = nil
    Audio.sounds[75].sfx = nil
    Audio.sounds[76].sfx = nil
    extrasounds.sound.sfx[77] = nil
    Audio.sounds[78].sfx = nil
    Audio.sounds[79].sfx = nil
    Audio.sounds[80].sfx = nil
    extrasounds.sound.sfx[81] = nil
    Audio.sounds[82].sfx = nil
    Audio.sounds[91].sfx = nil
    for i = 92,165 do
        extrasounds.sound.sfx[i] = nil
    end
end

return costume