local pm = require("playerManager")
local extrasounds = require("extrasounds")

local costume = {}

local eventsRegistered = false

function costume.onInit(p)
	Audio.sounds[1].sfx  = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/player-jump.ogg")
	Audio.sounds[2].sfx  = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/stomped.ogg")
	Audio.sounds[3].sfx  = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/block-hit.ogg")
	extrasounds.id[4]  = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/block-smash.ogg")
	Audio.sounds[5].sfx  = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/player-shrink.ogg")
	Audio.sounds[6].sfx  = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/player-grow.ogg")
	extrasounds.id[7]  = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/mushroom.ogg")
	extrasounds.id[8]  = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/player-died.ogg")
	Audio.sounds[9].sfx  = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/shell-hit.ogg")
	Audio.sounds[10].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/player-slide.ogg")
	Audio.sounds[11].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/item-dropped.ogg")
	Audio.sounds[12].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/has-item.ogg")
	Audio.sounds[13].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/camera-change.ogg")
	extrasounds.id[14] = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/coin.ogg")
	extrasounds.id[15] = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/1up.ogg")
	Audio.sounds[16].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/lava.ogg")
	Audio.sounds[17].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/warp.ogg")
	extrasounds.id[18] = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/fireball.ogg")
	Audio.sounds[19].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/level-win.ogg")
	Audio.sounds[20].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/boss-beat.ogg")
	Audio.sounds[21].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/dungeon-win.ogg")
	Audio.sounds[22].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/bullet-bill.ogg")
	Audio.sounds[23].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/grab.ogg")
	Audio.sounds[24].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/spring.ogg")
	Audio.sounds[25].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/hammer.ogg")
	Audio.sounds[29].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/do.ogg")
	Audio.sounds[31].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/key.ogg")
	Audio.sounds[32].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/pswitch.ogg")
	Audio.sounds[33].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/tail.ogg")
	Audio.sounds[34].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/racoon.ogg")
	Audio.sounds[35].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/boot.ogg")
	Audio.sounds[36].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/smash.ogg")
	Audio.sounds[37].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/thwomp.ogg")
	Audio.sounds[38].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/birdo-spit.ogg")
	Audio.sounds[39].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/birdo-hit.ogg")
	Audio.sounds[41].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/birdo-beat.ogg")
	Audio.sounds[42].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/npc-fireball.ogg")
	extrasounds.id[43] = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/fireworks.ogg")
	Audio.sounds[44].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/bowser-killed.ogg")
	Audio.sounds[46].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/door.ogg")
	Audio.sounds[47].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/message.ogg")
	Audio.sounds[48].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/yoshi.ogg")
	Audio.sounds[49].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/yoshi-hurt.ogg")
	Audio.sounds[50].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/yoshi-tongue.ogg")
	Audio.sounds[51].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/yoshi-egg.ogg")
	Audio.sounds[52].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/got-star.ogg")
	Audio.sounds[54].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/player-died2.ogg")
	Audio.sounds[55].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/yoshi-swallow.ogg")
	Audio.sounds[57].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/dry-bones.ogg")
	Audio.sounds[58].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/smw-checkpoint.ogg")
	extrasounds.id[59] = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/dragon-coin.ogg")
	Audio.sounds[61].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/smw-blaarg.ogg")
	Audio.sounds[62].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/wart-bubble.ogg")
	Audio.sounds[63].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/wart-die.ogg")
	Audio.sounds[71].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/climbing.ogg")
	Audio.sounds[72].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/swim.ogg")
	Audio.sounds[73].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/grab2.ogg")
	--Audio.sounds[74].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/saw.ogg")
	Audio.sounds[75].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/smb2-throw.ogg")
	Audio.sounds[76].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/smb2-hit.ogg")
	Audio.sounds[91].sfx = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/bubble.ogg")
	extrasounds.id93 = Audio.SfxOpen("costumes/luigi/3-SMB1-Retro-Modern/fireball.ogg")
	
	eventsRegistered = true
end

function costume.onCleanup(p)
		Audio.sounds[1].sfx  = nil	
	Audio.sounds[2].sfx  = nil
	Audio.sounds[3].sfx  = nil
	Audio.sounds[4].sfx  = nil
	Audio.sounds[5].sfx  = nil
	Audio.sounds[6].sfx  = nil
	Audio.sounds[7].sfx  = nil
	extrasounds.id[8] = Audio.SfxOpen(Misc.resolveSoundFile("player-died"))
	Audio.sounds[9].sfx  = nil
	Audio.sounds[10].sfx = nil
	Audio.sounds[11].sfx = nil
	Audio.sounds[12].sfx = nil
	Audio.sounds[13].sfx = nil
	extrasounds.id[14] = Audio.SfxOpen(Misc.resolveSoundFile("sound/coin.ogg"))
	extrasounds.id[15] = Audio.SfxOpen(Misc.resolveSoundFile("sound/1up.ogg"))
	Audio.sounds[16].sfx = nil
	Audio.sounds[17].sfx = nil
	extrasounds.id[18] = Audio.SfxOpen(Misc.resolveSoundFile("sound/fireball.ogg"))
	Audio.sounds[19].sfx = nil
	Audio.sounds[20].sfx = nil
	Audio.sounds[21].sfx = nil
	Audio.sounds[22].sfx = nil
	Audio.sounds[23].sfx = nil
	Audio.sounds[24].sfx = nil
	Audio.sounds[25].sfx = nil
	Audio.sounds[29].sfx = nil
	Audio.sounds[31].sfx = nil
	Audio.sounds[32].sfx = nil
	Audio.sounds[33].sfx = nil
	Audio.sounds[34].sfx = nil
	Audio.sounds[35].sfx = nil
	Audio.sounds[36].sfx = nil
	Audio.sounds[37].sfx = nil
	Audio.sounds[38].sfx = nil
	Audio.sounds[39].sfx = nil
	Audio.sounds[41].sfx = nil
	Audio.sounds[42].sfx = nil
	Audio.sounds[43].sfx = nil
	Audio.sounds[44].sfx = nil
	Audio.sounds[46].sfx = nil
	Audio.sounds[47].sfx = nil
	Audio.sounds[48].sfx = nil
	Audio.sounds[49].sfx = nil
	Audio.sounds[50].sfx = nil
	Audio.sounds[51].sfx = nil
	Audio.sounds[52].sfx = nil
	Audio.sounds[54].sfx = nil
	Audio.sounds[55].sfx = nil
	Audio.sounds[56].sfx = nil
	Audio.sounds[57].sfx = nil
	Audio.sounds[58].sfx = nil
	Audio.sounds[59].sfx = nil
	Audio.sounds[61].sfx = nil
	Audio.sounds[62].sfx = nil
	Audio.sounds[63].sfx = nil
	Audio.sounds[71].sfx = nil
	Audio.sounds[72].sfx = nil
	Audio.sounds[73].sfx = nil
	Audio.sounds[75].sfx = nil
	Audio.sounds[76].sfx = nil
	Audio.sounds[77].sfx = nil
	Audio.sounds[78].sfx = nil
	Audio.sounds[79].sfx = nil
	Audio.sounds[80].sfx = nil
	Audio.sounds[81].sfx = nil
	Audio.sounds[82].sfx = nil
	Audio.sounds[91].sfx = nil
	extrasounds.id92 = Audio.SfxOpen(Misc.resolveSoundFile("sound/sprout-vine.ogg"))
	extrasounds.id93 = Audio.SfxOpen(Misc.resolveSoundFile("sound/iceball.ogg"))
	extrasounds.id94 = Audio.SfxOpen(Misc.resolveSoundFile("sound/yi_freeze.ogg"))
	extrasounds.id95 = Audio.SfxOpen(Misc.resolveSoundFile("sound/yi_icebreak.ogg"))
	extrasounds.id96 = Audio.SfxOpen(Misc.resolveSoundFile("sound/2up.ogg"))
	extrasounds.id97 = Audio.SfxOpen(Misc.resolveSoundFile("sound/3up.ogg"))
	extrasounds.id98 = Audio.SfxOpen(Misc.resolveSoundFile("sound/5up.ogg"))
	extrasounds.id99 = Audio.SfxOpen(Misc.resolveSoundFile("sound/dragon-coin-get2.ogg"))
	extrasounds.id100 = Audio.SfxOpen(Misc.resolveSoundFile("sound/dragon-coin-get3.ogg"))
	extrasounds.id101 = Audio.SfxOpen(Misc.resolveSoundFile("sound/dragon-coin-get4.ogg"))
	extrasounds.id102 = Audio.SfxOpen(Misc.resolveSoundFile("sound/dragon-coin-get5.ogg"))
	extrasounds.id103 = Audio.SfxOpen(Misc.resolveSoundFile("sound/cherry.ogg"))
end

return costume